### ISSUE TITLE
where is the file 'LinguSocial.xcodeproj'

### ISSUE THREAD

**Issue by d1bug** [marcelgoya/cordova-plugin-iosrtc#1]
Dear author，Can you give me the file 'LinguSocial.xcodeproj' or uploading it.
Or you can teach me how to set it.

**Comment by marcelgoya** [comment]
Hi, sorry this is just a test repo I've created. It's not for public use. What are you using the webrtc plugin for anyway? I've forked because I wanted to upgrade to the latest webrtc version.

**Comment by d1bug** [comment]
Just for learn.
I know how to used it,just rename it to my project's name,is right?

**Comment by d1bug** [comment]
> Hi, sorry this is just a test repo I've created. It's not for public use. What are you using the webrtc plugin for anyway? I've forked because I wanted to upgrade to the latest webrtc version.

Just for learn.
I know how to used it,just rename it to my project's name,is right?

**Comment by d1bug** [comment]
Are you chinese?

**Comment by marcelgoya** [comment]
Nope, German. I don't understand why you're not forking the official repo?

**Comment by d1bug** [comment]
I used the official repo,but my app always crashed,and had many problem....

**Comment by marcelgoya** [comment]
Like I've said, my repo is just a test repo so I don't think the result will be any better for you

**Comment by d1bug** [comment]
I know you,my app always crashed,i think is not compling the lastest of libwebrtc

**Comment by d1bug** [comment]
And i used webrtc-build-script to comiple it but no file in webrtc source code .

**Comment by d1bug** [comment]
When you could to upgrade it ???
Or can you teaching me to developer the cordova plugin?

**Comment by marcelgoya** [comment]
Sorry but I won't be able to help you because I wasn't able to upgrade the plugin either, therefore would recommend you to contact the people who developed the plugin and ask them for assistance.

**Comment by d1bug** [comment]
Didn't you say upgrading to the latest webrtc? Can you bring me?

**Comment by marcelgoya** [comment]
I think we got lost in translation. I said that I did not upgrade because it was too difficult.

**Comment by marcelgoya** [comment]
I can not help you. please ask the developers of the original plugin.

**Comment by marcelgoya** [comment]
No problem, no I didn't

**Comment by d1bug** [comment]
Cry,I used the offical plugin.....
I asked the author but no answer....

**Comment by marcelgoya** [comment]
So we are both in the same boat :(
